<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FAREL36J" failures="7" tests="31" name="restassuredtests" time="18.16" errors="0" timestamp="30 Mar 2022 12:01:17 GMT">
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="@BeforeClass deleteEmployee" time="0.82">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD.deleteEmployee(TC005_DELETE_EMPLOYEE_RECORD.java:34)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 30 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkContentLength" time="0.004"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkContentType" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES.checkContentType(TC001_GET_ALL_EMPLOYEES.java:75)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkCookies" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkResponseBody" time="0.027"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkStatusCode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES.checkStatusCode(TC001_GET_ALL_EMPLOYEES.java:43)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkcontntEncoding" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkserverType" time="0.002"/>
  <testcase classname="com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES" name="checkstatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapis.testCases.TC001_GET_ALL_EMPLOYEES.checkstatusLine(TC001_GET_ALL_EMPLOYEES.java:65)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkContentLength" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkContentType" time="0.002"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkResponseBody" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkResponseTime" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkserverType" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC002_GET_SINGLE_EMPLOYEE_RECORD" name="checkstatusLine" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD" name="checkContentType" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD.checkContentType(TC003_POST_EMPLOYEE_RECORD.java:75)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD" name="checkResponseBody" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD.checkResponseBody(TC003_POST_EMPLOYEE_RECORD.java:53)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD" name="checkStatusCode" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD.checkStatusCode(TC003_POST_EMPLOYEE_RECORD.java:62)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD" name="checkserverType" time="0.0"/>
  <testcase classname="com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD" name="checkstatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapis.testCases.TC003_POST_EMPLOYEE_RECORD.checkstatusLine(TC003_POST_EMPLOYEE_RECORD.java:68)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase classname="com.employeeapis.testCases.TC004_PUT_EMPLOYEE_RECORD" name="checkContentType" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC004_PUT_EMPLOYEE_RECORD" name="checkResponseBody" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC004_PUT_EMPLOYEE_RECORD" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC004_PUT_EMPLOYEE_RECORD" name="checkserverType" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC004_PUT_EMPLOYEE_RECORD" name="checkstatusLine" time="0.001"/>
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="checkContentType" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="checkStatusCode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="checkserverType" time="0.0">
    <skipped/>
  </testcase> <!-- checkserverType -->
  <testcase classname="com.employeeapis.testCases.TC005_DELETE_EMPLOYEE_RECORD" name="checkstatusLine" time="0.0">
    <skipped/>
  </testcase> <!-- checkstatusLine -->
</testsuite> <!-- restassuredtests -->
